version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "8443:8443"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${API_URL}
    env_file:
      - ./frontend/.env
    ports:
      - "8080:80"
    restart: unless-stopped
